2024-12-02 11:47:42,574 INFO    StreamThr :1845 [internal.py:wandb_internal():86] W&B internal server running at pid: 1845, started at: 2024-12-02 11:47:42.573402
2024-12-02 11:47:42,575 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: status
2024-12-02 11:47:42,578 INFO    WriterThread:1845 [datastore.py:open_for_write():87] open: ./wandb/run-20241202_114742-wrx7vlmb/run-wrx7vlmb.wandb
2024-12-02 11:47:42,579 DEBUG   SenderThread:1845 [sender.py:send():379] send: header
2024-12-02 11:47:42,867 DEBUG   SenderThread:1845 [sender.py:send():379] send: run
2024-12-02 11:47:42,875 INFO    SenderThread:1845 [sender.py:_setup_resume():749] checking resume status for None/Thermostability/wrx7vlmb
2024-12-02 11:47:47,868 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:47:52,869 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:47:57,870 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:48:02,871 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:48:07,872 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:48:12,874 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:48:17,875 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:48:22,876 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:48:27,877 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:48:32,878 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:48:37,879 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:48:42,880 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:48:47,765 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: check_version
2024-12-02 11:48:47,817 INFO    SenderThread:1845 [dir_watcher.py:__init__():211] watching files in: ./wandb/run-20241202_114742-wrx7vlmb/files
2024-12-02 11:48:47,817 INFO    SenderThread:1845 [sender.py:_start_run_threads():1124] run started: wrx7vlmb with start time 1733140062.573802
2024-12-02 11:48:47,817 DEBUG   SenderThread:1845 [sender.py:send_request():406] send_request: check_version
2024-12-02 11:48:47,817 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: status_report
2024-12-02 11:48:48,127 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: run_start
2024-12-02 11:48:48,132 DEBUG   HandlerThread:1845 [system_info.py:__init__():26] System info init
2024-12-02 11:48:48,132 DEBUG   HandlerThread:1845 [system_info.py:__init__():41] System info init done
2024-12-02 11:48:48,132 INFO    HandlerThread:1845 [system_monitor.py:start():194] Starting system monitor
2024-12-02 11:48:48,132 INFO    SystemMonitor:1845 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-12-02 11:48:48,132 INFO    HandlerThread:1845 [system_monitor.py:probe():214] Collecting system info
2024-12-02 11:48:48,133 INFO    SystemMonitor:1845 [interfaces.py:start():190] Started cpu monitoring
2024-12-02 11:48:48,133 INFO    SystemMonitor:1845 [interfaces.py:start():190] Started disk monitoring
2024-12-02 11:48:48,134 INFO    SystemMonitor:1845 [interfaces.py:start():190] Started gpu monitoring
2024-12-02 11:48:48,135 INFO    SystemMonitor:1845 [interfaces.py:start():190] Started memory monitoring
2024-12-02 11:48:48,136 INFO    SystemMonitor:1845 [interfaces.py:start():190] Started network monitoring
2024-12-02 11:48:48,163 DEBUG   HandlerThread:1845 [system_info.py:probe():150] Probing system
2024-12-02 11:48:48,168 DEBUG   HandlerThread:1845 [system_info.py:_probe_git():135] Probing git
2024-12-02 11:48:48,178 DEBUG   HandlerThread:1845 [system_info.py:_probe_git():143] Probing git done
2024-12-02 11:48:48,178 DEBUG   HandlerThread:1845 [system_info.py:probe():198] Probing system done
2024-12-02 11:48:48,178 DEBUG   HandlerThread:1845 [system_monitor.py:probe():223] {'os': 'Linux-5.4.250-2-velinux1u1-amd64-x86_64-with-glibc2.31', 'python': '3.9.17', 'heartbeatAt': '2024-12-02T11:48:48.163747', 'startedAt': '2024-12-02T11:47:42.543888', 'docker': None, 'cuda': None, 'args': ('--config', 'represent_learning/config/Thermostability/ProfileBFN_650M.yaml', '--model.save_path', 'checkpoints/Thermostability_trainThermostability_ProfileBFN_650M', '--model_checkpoint.dirpath', 'checkpoints/Thermostability_trainThermostability_ProfileBFN_650M', '--Trainer.logger', 'wandb'), 'state': 'running', 'program': '/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/training.py', 'codePathLocal': 'represent_learning/training.py', 'codePath': 'represent_learning/training.py', 'git': {'remote': 'git@github.com:AlgoMole/ProfileBFN-pro.git', 'commit': '712a087b708854d75a38eda32ce0556f7d2d2b0e'}, 'email': None, 'root': '/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro', 'host': 't-20241202194200-mb7t8-worker-0', 'username': 'root', 'executable': '/root/miniconda3/bin/python', 'cpu_count': 56, 'cpu_count_logical': 50, 'cpu_freq': {'current': 2294.6080000000034, 'min': 0.0, 'max': 0.0}, 'cpu_freq_per_core': [{'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}, {'current': 2294.608, 'min': 0.0, 'max': 0.0}], 'disk': {'/': {'total': 3519.7501831054688, 'used': 618.7729721069336}}, 'gpu': 'NVIDIA A100-SXM4-80GB', 'gpu_count': 4, 'gpu_devices': [{'name': 'NVIDIA A100-SXM4-80GB', 'memory_total': 85198045184}, {'name': 'NVIDIA A100-SXM4-80GB', 'memory_total': 85198045184}, {'name': 'NVIDIA A100-SXM4-80GB', 'memory_total': 85198045184}, {'name': 'NVIDIA A100-SXM4-80GB', 'memory_total': 85198045184}], 'memory': {'total': 930.0}}
2024-12-02 11:48:48,179 INFO    HandlerThread:1845 [system_monitor.py:probe():224] Finished collecting system info
2024-12-02 11:48:48,179 INFO    HandlerThread:1845 [system_monitor.py:probe():227] Publishing system info
2024-12-02 11:48:48,179 DEBUG   HandlerThread:1845 [system_info.py:_save_conda():207] Saving list of conda packages installed into the current environment
2024-12-02 11:48:48,819 INFO    Thread-12 :1845 [dir_watcher.py:_on_file_created():271] file/dir created: ./wandb/run-20241202_114742-wrx7vlmb/files/conda-environment.yaml
2024-12-02 11:48:51,249 DEBUG   HandlerThread:1845 [system_info.py:_save_conda():222] Saving conda packages done
2024-12-02 11:48:51,252 INFO    HandlerThread:1845 [system_monitor.py:probe():229] Finished publishing system info
2024-12-02 11:48:51,256 DEBUG   SenderThread:1845 [sender.py:send():379] send: files
2024-12-02 11:48:51,256 INFO    SenderThread:1845 [sender.py:_save_file():1390] saving file wandb-metadata.json with policy now
2024-12-02 11:48:51,375 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: python_packages
2024-12-02 11:48:51,375 DEBUG   SenderThread:1845 [sender.py:send_request():406] send_request: python_packages
2024-12-02 11:48:51,378 DEBUG   SenderThread:1845 [sender.py:send():379] send: telemetry
2024-12-02 11:48:51,378 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: internal_messages
2024-12-02 11:48:51,378 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: stop_status
2024-12-02 11:48:51,379 DEBUG   SenderThread:1845 [sender.py:send():379] send: metric
2024-12-02 11:48:51,379 DEBUG   SenderThread:1845 [sender.py:send_request():406] send_request: stop_status
2024-12-02 11:48:51,819 INFO    Thread-12 :1845 [dir_watcher.py:_on_file_modified():288] file/dir modified: ./wandb/run-20241202_114742-wrx7vlmb/files/conda-environment.yaml
2024-12-02 11:48:51,819 INFO    Thread-12 :1845 [dir_watcher.py:_on_file_created():271] file/dir created: ./wandb/run-20241202_114742-wrx7vlmb/files/requirements.txt
2024-12-02 11:48:51,819 INFO    Thread-12 :1845 [dir_watcher.py:_on_file_created():271] file/dir created: ./wandb/run-20241202_114742-wrx7vlmb/files/wandb-metadata.json
2024-12-02 11:48:56,823 INFO    wandb-upload_0:1845 [upload_job.py:push():131] Uploaded file /tmp/tmp_3s1rv22wandb/qi0hrmqx-wandb-metadata.json
2024-12-02 11:49:17,714 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:49:17,716 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:49:17,716 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: internal_messages
2024-12-02 11:49:22,821 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:49:25,208 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: status_report
2024-12-02 11:49:27,821 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:49:28,971 DEBUG   SenderThread:1845 [sender.py:send():379] send: telemetry
2024-12-02 11:49:28,972 DEBUG   SenderThread:1845 [sender.py:send():379] send: metric
2024-12-02 11:49:28,972 WARNING SenderThread:1845 [sender.py:send_metric():1341] Seen metric with glob (shouldn't happen)
2024-12-02 11:49:29,830 INFO    Thread-12 :1845 [dir_watcher.py:_on_file_modified():288] file/dir modified: ./wandb/run-20241202_114742-wrx7vlmb/files/config.yaml
2024-12-02 11:49:29,830 INFO    Thread-12 :1845 [dir_watcher.py:_on_file_created():271] file/dir created: ./wandb/run-20241202_114742-wrx7vlmb/files/output.log
2024-12-02 11:49:31,831 INFO    Thread-12 :1845 [dir_watcher.py:_on_file_modified():288] file/dir modified: ./wandb/run-20241202_114742-wrx7vlmb/files/output.log
2024-12-02 11:49:32,714 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: internal_messages
2024-12-02 11:49:32,950 DEBUG   SenderThread:1845 [sender.py:send():379] send: exit
2024-12-02 11:49:32,951 INFO    SenderThread:1845 [sender.py:send_exit():586] handling exit code: 1
2024-12-02 11:49:32,951 INFO    SenderThread:1845 [sender.py:send_exit():588] handling runtime: 44
2024-12-02 11:49:32,952 INFO    SenderThread:1845 [sender.py:_save_file():1390] saving file wandb-summary.json with policy end
2024-12-02 11:49:32,952 INFO    SenderThread:1845 [sender.py:send_exit():594] send defer
2024-12-02 11:49:32,952 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: defer
2024-12-02 11:49:32,953 INFO    HandlerThread:1845 [handler.py:handle_request_defer():172] handle defer: 0
2024-12-02 11:49:32,953 DEBUG   SenderThread:1845 [sender.py:send_request():406] send_request: defer
2024-12-02 11:49:32,953 INFO    SenderThread:1845 [sender.py:send_request_defer():610] handle sender defer: 0
2024-12-02 11:49:32,953 INFO    SenderThread:1845 [sender.py:transition_state():614] send defer: 1
2024-12-02 11:49:32,953 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: defer
2024-12-02 11:49:32,953 INFO    HandlerThread:1845 [handler.py:handle_request_defer():172] handle defer: 1
2024-12-02 11:49:32,953 DEBUG   SenderThread:1845 [sender.py:send_request():406] send_request: defer
2024-12-02 11:49:32,953 INFO    SenderThread:1845 [sender.py:send_request_defer():610] handle sender defer: 1
2024-12-02 11:49:32,953 INFO    SenderThread:1845 [sender.py:transition_state():614] send defer: 2
2024-12-02 11:49:32,953 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: defer
2024-12-02 11:49:32,953 INFO    HandlerThread:1845 [handler.py:handle_request_defer():172] handle defer: 2
2024-12-02 11:49:32,953 INFO    HandlerThread:1845 [system_monitor.py:finish():203] Stopping system monitor
2024-12-02 11:49:32,954 INFO    HandlerThread:1845 [interfaces.py:finish():202] Joined cpu monitor
2024-12-02 11:49:32,954 DEBUG   SystemMonitor:1845 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-12-02 11:49:32,954 INFO    HandlerThread:1845 [interfaces.py:finish():202] Joined disk monitor
2024-12-02 11:49:32,954 DEBUG   SystemMonitor:1845 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-12-02 11:49:32,955 DEBUG   SystemMonitor:1845 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-12-02 11:49:33,264 INFO    HandlerThread:1845 [interfaces.py:finish():202] Joined gpu monitor
2024-12-02 11:49:33,265 INFO    HandlerThread:1845 [interfaces.py:finish():202] Joined memory monitor
2024-12-02 11:49:33,265 INFO    HandlerThread:1845 [interfaces.py:finish():202] Joined network monitor
2024-12-02 11:49:33,265 DEBUG   SenderThread:1845 [sender.py:send_request():406] send_request: defer
2024-12-02 11:49:33,265 INFO    SenderThread:1845 [sender.py:send_request_defer():610] handle sender defer: 2
2024-12-02 11:49:33,265 INFO    SenderThread:1845 [sender.py:transition_state():614] send defer: 3
2024-12-02 11:49:33,265 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: defer
2024-12-02 11:49:33,265 INFO    HandlerThread:1845 [handler.py:handle_request_defer():172] handle defer: 3
2024-12-02 11:49:33,267 DEBUG   SenderThread:1845 [sender.py:send():379] send: stats
2024-12-02 11:49:33,268 DEBUG   SenderThread:1845 [sender.py:send_request():406] send_request: defer
2024-12-02 11:49:33,268 INFO    SenderThread:1845 [sender.py:send_request_defer():610] handle sender defer: 3
2024-12-02 11:49:33,268 INFO    SenderThread:1845 [sender.py:transition_state():614] send defer: 4
2024-12-02 11:49:33,268 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: defer
2024-12-02 11:49:33,268 INFO    HandlerThread:1845 [handler.py:handle_request_defer():172] handle defer: 4
2024-12-02 11:49:33,268 DEBUG   SenderThread:1845 [sender.py:send_request():406] send_request: defer
2024-12-02 11:49:33,268 INFO    SenderThread:1845 [sender.py:send_request_defer():610] handle sender defer: 4
2024-12-02 11:49:33,268 INFO    SenderThread:1845 [sender.py:transition_state():614] send defer: 5
2024-12-02 11:49:33,269 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: defer
2024-12-02 11:49:33,269 INFO    HandlerThread:1845 [handler.py:handle_request_defer():172] handle defer: 5
2024-12-02 11:49:33,269 DEBUG   SenderThread:1845 [sender.py:send():379] send: summary
2024-12-02 11:49:33,270 INFO    SenderThread:1845 [sender.py:_save_file():1390] saving file wandb-summary.json with policy end
2024-12-02 11:49:33,270 DEBUG   SenderThread:1845 [sender.py:send_request():406] send_request: defer
2024-12-02 11:49:33,270 INFO    SenderThread:1845 [sender.py:send_request_defer():610] handle sender defer: 5
2024-12-02 11:49:33,270 INFO    SenderThread:1845 [sender.py:transition_state():614] send defer: 6
2024-12-02 11:49:33,270 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: defer
2024-12-02 11:49:33,270 INFO    HandlerThread:1845 [handler.py:handle_request_defer():172] handle defer: 6
2024-12-02 11:49:33,270 DEBUG   SenderThread:1845 [sender.py:send_request():406] send_request: defer
2024-12-02 11:49:33,270 INFO    SenderThread:1845 [sender.py:send_request_defer():610] handle sender defer: 6
2024-12-02 11:49:33,273 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: status_report
2024-12-02 11:49:33,831 INFO    Thread-12 :1845 [dir_watcher.py:_on_file_created():271] file/dir created: ./wandb/run-20241202_114742-wrx7vlmb/files/wandb-summary.json
2024-12-02 11:49:33,950 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: poll_exit
2024-12-02 11:49:35,832 INFO    Thread-12 :1845 [dir_watcher.py:_on_file_modified():288] file/dir modified: ./wandb/run-20241202_114742-wrx7vlmb/files/output.log
2024-12-02 11:49:36,759 INFO    SenderThread:1845 [sender.py:transition_state():614] send defer: 7
2024-12-02 11:49:36,760 DEBUG   SenderThread:1845 [sender.py:send_request():406] send_request: poll_exit
2024-12-02 11:49:36,760 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: defer
2024-12-02 11:49:36,760 INFO    HandlerThread:1845 [handler.py:handle_request_defer():172] handle defer: 7
2024-12-02 11:49:36,760 DEBUG   SenderThread:1845 [sender.py:send_request():406] send_request: defer
2024-12-02 11:49:36,760 INFO    SenderThread:1845 [sender.py:send_request_defer():610] handle sender defer: 7
2024-12-02 11:49:36,832 INFO    Thread-12 :1845 [dir_watcher.py:_on_file_modified():288] file/dir modified: ./wandb/run-20241202_114742-wrx7vlmb/files/config.yaml
2024-12-02 11:49:36,951 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: poll_exit
2024-12-02 11:49:39,010 INFO    SenderThread:1845 [sender.py:transition_state():614] send defer: 8
2024-12-02 11:49:39,011 DEBUG   SenderThread:1845 [sender.py:send_request():406] send_request: poll_exit
2024-12-02 11:49:39,011 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: defer
2024-12-02 11:49:39,011 INFO    HandlerThread:1845 [handler.py:handle_request_defer():172] handle defer: 8
2024-12-02 11:49:39,011 DEBUG   SenderThread:1845 [sender.py:send_request():406] send_request: defer
2024-12-02 11:49:39,011 INFO    SenderThread:1845 [sender.py:send_request_defer():610] handle sender defer: 8
2024-12-02 11:49:39,011 INFO    SenderThread:1845 [job_builder.py:build():318] Attempting to build job artifact
2024-12-02 11:49:39,012 INFO    SenderThread:1845 [job_builder.py:_get_source_type():455] is repo sourced job
2024-12-02 11:49:39,040 INFO    SenderThread:1845 [job_builder.py:build():431] adding wandb-job metadata file
2024-12-02 11:49:39,043 INFO    SenderThread:1845 [sender.py:transition_state():614] send defer: 9
2024-12-02 11:49:39,043 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: defer
2024-12-02 11:49:39,043 DEBUG   SenderThread:1845 [sender.py:send():379] send: artifact
2024-12-02 11:49:39,043 INFO    HandlerThread:1845 [handler.py:handle_request_defer():172] handle defer: 9
2024-12-02 11:49:39,833 INFO    Thread-12 :1845 [dir_watcher.py:_on_file_modified():288] file/dir modified: ./wandb/run-20241202_114742-wrx7vlmb/files/output.log
2024-12-02 11:49:39,953 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: poll_exit
2024-12-02 11:49:44,955 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:49:49,956 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:49:54,957 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:49:59,959 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:50:04,960 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:50:09,962 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:50:14,963 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:50:19,965 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:50:24,967 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:50:29,968 DEBUG   HandlerThread:1845 [handler.py:handle_request():146] handle_request: keepalive
2024-12-02 11:50:31,795 WARNING StreamThr :1845 [internal.py:is_dead():414] Internal process exiting, parent pid 1664 disappeared
2024-12-02 11:50:31,795 ERROR   StreamThr :1845 [internal.py:wandb_internal():152] Internal process shutdown.
2024-12-02 11:50:31,959 INFO    WriterThread:1845 [datastore.py:close():296] close: ./wandb/run-20241202_114742-wrx7vlmb/run-wrx7vlmb.wandb
2024-12-02 11:50:31,969 INFO    HandlerThread:1845 [handler.py:finish():866] shutting down handler
2024-12-02 11:50:37,238 INFO    SenderThread:1845 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/root/miniconda3/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/root/miniconda3/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/root/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f709123aa00>, 'Connection to api.wandb.ai timed out. (connect timeout=20)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.9/site-packages/requests/adapters.py", line 487, in send
    resp = conn.urlopen(
  File "/root/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f709123aa00>, 'Connection to api.wandb.ai timed out. (connect timeout=20)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/root/miniconda3/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
  File "/root/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/requests/adapters.py", line 508, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f709123aa00>, 'Connection to api.wandb.ai timed out. (connect timeout=20)'))
2024-12-02 11:50:53,634 INFO    SenderThread:1845 [sender.py:send_artifact():1468] sent artifact job-git_github.com_AlgoMole_ProfileBFN-pro.git_represent_learning_training.py - {'id': 'QXJ0aWZhY3Q6MTM1NjgxMjg5MA==', 'state': 'COMMITTED', 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjUwMDE0MTQ5MA==', 'latestArtifact': {'id': 'QXJ0aWZhY3Q6MTM1NjgxMjg5MA==', 'versionIndex': 0}}}
2024-12-02 11:50:53,636 INFO    SenderThread:1845 [sender.py:finish():1546] shutting down sender
2024-12-02 11:50:53,637 INFO    SenderThread:1845 [dir_watcher.py:finish():358] shutting down directory watcher
2024-12-02 11:50:53,843 INFO    SenderThread:1845 [dir_watcher.py:finish():388] scan: ./wandb/run-20241202_114742-wrx7vlmb/files
2024-12-02 11:50:53,844 INFO    SenderThread:1845 [dir_watcher.py:finish():402] scan save: ./wandb/run-20241202_114742-wrx7vlmb/files/conda-environment.yaml conda-environment.yaml
2024-12-02 11:50:53,844 INFO    SenderThread:1845 [dir_watcher.py:finish():402] scan save: ./wandb/run-20241202_114742-wrx7vlmb/files/wandb-metadata.json wandb-metadata.json
2024-12-02 11:50:53,844 INFO    SenderThread:1845 [dir_watcher.py:finish():402] scan save: ./wandb/run-20241202_114742-wrx7vlmb/files/config.yaml config.yaml
2024-12-02 11:50:53,847 INFO    SenderThread:1845 [dir_watcher.py:finish():402] scan save: ./wandb/run-20241202_114742-wrx7vlmb/files/requirements.txt requirements.txt
2024-12-02 11:50:53,847 INFO    SenderThread:1845 [dir_watcher.py:finish():402] scan save: ./wandb/run-20241202_114742-wrx7vlmb/files/wandb-summary.json wandb-summary.json
2024-12-02 11:50:53,849 INFO    SenderThread:1845 [dir_watcher.py:finish():402] scan save: ./wandb/run-20241202_114742-wrx7vlmb/files/output.log output.log
2024-12-02 11:50:53,851 INFO    SenderThread:1845 [file_pusher.py:finish():172] shutting down file pusher
2024-12-02 11:50:53,854 INFO    SenderThread:1845 [file_pusher.py:join():178] waiting for file pusher
2024-12-02 11:50:57,967 INFO    wandb-upload_4:1845 [upload_job.py:push():131] Uploaded file ./wandb/run-20241202_114742-wrx7vlmb/files/output.log
2024-12-02 11:50:58,233 INFO    wandb-upload_3:1845 [upload_job.py:push():131] Uploaded file ./wandb/run-20241202_114742-wrx7vlmb/files/wandb-summary.json
2024-12-02 11:50:58,653 WARNING FileStreamThread:1845 [file_stream.py:request_with_retry():687] requests_with_retry encountered retryable exception: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/files/algomole/Thermostability/wrx7vlmb/file_stream. func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x7f709159b160>>, timeout=180.0), args: ('https://api.wandb.ai/files/algomole/Thermostability/wrx7vlmb/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{"_wandb": {"runtime": 44}}']}, 'wandb-events.jsonl': {'offset': 0, 'content': ['{"system.network.sent": 1968795.75, "system.network.recv": 1965425.12, "system.cpu": 1.04, "system.cpu.0.cpu_percent": 14.89, "system.cpu.1.cpu_percent": 1.39, "system.cpu.2.cpu_percent": 2.38, "system.cpu.3.cpu_percent": 1.75, "system.cpu.4.cpu_percent": 2.56, "system.cpu.5.cpu_percent": 7.5, "system.cpu.6.cpu_percent": 2.12, "system.cpu.7.cpu_percent": 1.19, "system.cpu.8.cpu_percent": 1.88, "system.cpu.9.cpu_percent": 1.06, "system.cpu.10.cpu_percent": 2.19, "system.cpu.11.cpu_percent": 1.31, "system.cpu.12.cpu_percent": 1.94, "system.cpu.13.cpu_percent": 1.0, "system.cpu.14.cpu_percent": 4.75, "system.cpu.15.cpu_percent": 2.62, "system.cpu.16.cpu_percent": 2.19, "system.cpu.17.cpu_percent": 1.56, "system.cpu.18.cpu_percent": 5.85, "system.cpu.19.cpu_percent": 1.06, "system.cpu.20.cpu_percent": 34.41, "system.cpu.21.cpu_percent": 1.31, "system.cpu.22.cpu_percent": 8.51, "system.cpu.23.cpu_percent": 1.12, "system.cpu.24.cpu_percent": 27.81, "system.cpu.25.cpu_percent": 1.56, "system.cpu.26.cpu_percent": 2.81, "system.cpu.27.cpu_percent": 1.38, "system.cpu.28.cpu_percent": 3.31, "system.cpu.29.cpu_percent": 2.38, "system.cpu.30.cpu_percent": 4.8, "system.cpu.31.cpu_percent": 1.19, "system.cpu.32.cpu_percent": 10.11, "system.cpu.33.cpu_percent": 1.38, "system.cpu.34.cpu_percent": 4.05, "system.cpu.35.cpu_percent": 1.06, "system.cpu.36.cpu_percent": 12.14, "system.cpu.37.cpu_percent": 1.19, "system.cpu.38.cpu_percent": 4.65, "system.cpu.39.cpu_percent": 1.12, "system.cpu.40.cpu_percent": 2.88, "system.cpu.41.cpu_percent": 1.06, "system.cpu.42.cpu_percent": 21.11, "system.cpu.43.cpu_percent": 1.06, "system.cpu.44.cpu_percent": 23.07, "system.cpu.45.cpu_percent": 1.69, "system.cpu.46.cpu_percent": 7.38, "system.cpu.47.cpu_percent": 45.81, "system.cpu.48.cpu_percent": 12.49, "system.cpu.49.cpu_percent": 0.94, "system.cpu.50.cpu_percent": 16.24, "system.cpu.51.cpu_percent": 1.06, "system.cpu.52.cpu_percent": 1.5, "system.cpu.53.cpu_percent": 51.2, "system.cpu.54.cpu_percent": 1.94, "system.cpu.55.cpu_percent": 25.67, "system.cpu.56.cpu_percent": 12.59, "system.cpu.57.cpu_percent": 1.31, "system.cpu.58.cpu_percent": 27.06, "system.cpu.59.cpu_percent": 25.94, "system.cpu.60.cpu_percent": 2.44, "system.cpu.61.cpu_percent": 1.31, "system.cpu.62.cpu_percent": 5.45, "system.cpu.63.cpu_percent": 2.06, "system.cpu.64.cpu_percent": 2.38, "system.cpu.65.cpu_percent": 1.62, "system.cpu.66.cpu_percent": 2.88, "system.cpu.67.cpu_percent": 1.31, "system.cpu.68.cpu_percent": 44.03, "system.cpu.69.cpu_percent": 1.25, "system.cpu.70.cpu_percent": 12.3, "system.cpu.71.cpu_percent": 1.38, "system.cpu.72.cpu_percent": 2.19, "system.cpu.73.cpu_percent": 6.59, "system.cpu.74.cpu_percent": 6.79, "system.cpu.75.cpu_percent": 1.5, "system.cpu.76.cpu_percent": 43.95, "system.cpu.77.cpu_percent": 1.44, "system.cpu.78.cpu_percent": 11.24, "system.cpu.79.cpu_percent": 3.06, "system.cpu.80.cpu_percent": 2.38, "system.cpu.81.cpu_percent": 1.5, "system.cpu.82.cpu_percent": 7.55, "system.cpu.83.cpu_percent": 1.19, "system.cpu.84.cpu_percent": 16.52, "system.cpu.85.cpu_percent": 1.25, "system.cpu.86.cpu_percent": 2.19, "system.cpu.87.cpu_percent": 1.81, "system.cpu.88.cpu_percent": 3.12, "system.cpu.89.cpu_percent": 1.31, "system.cpu.90.cpu_percent": 3.0, "system.cpu.91.cpu_percent": 2.12, "system.cpu.92.cpu_percent": 16.23, "system.cpu.93.cpu_percent": 1.19, "system.cpu.94.cpu_percent": 26.04, "system.cpu.95.cpu_percent": 1.44, "system.cpu.96.cpu_percent": 17.49, "system.cpu.97.cpu_percent": 1.38, "system.cpu.98.cpu_percent": 2.31, "system.cpu.99.cpu_percent": 3.0, "system.cpu.100.cpu_percent": 9.64, "system.cpu.101.cpu_percent": 1.75, "system.cpu.102.cpu_percent": 2.0, "system.cpu.103.cpu_percent": 1.56, "system.cpu.104.cpu_percent": 2.06, "system.cpu.105.cpu_percent": 1.94, "system.cpu.106.cpu_percent": 1.69, "system.cpu.107.cpu_percent": 40.56, "system.cpu.108.cpu_percent": 15.8, "system.cpu.109.cpu_percent": 1.38, "system.cpu.110.cpu_percent": 11.55, "system.cpu.111.cpu_percent": 5.26, "system.proc.cpu.threads": 21, "system.disk.\\\\.usagePercent": 18.5, "system.disk.\\\\.usageGB": 618.77, "system.disk.in": 0.97, "system.disk.out": 7.71, "system.proc.memory.availableMB": 912332.14, "system.memory": 4.21, "system.proc.memory.rssMB": 10199.95, "system.proc.memory.percent": 1.07, "system.gpu.0.memoryAllocated": 5.08, "system.gpu.1.memoryAllocated": 0.0, "system.gpu.2.memoryAllocated": 0.0, "system.gpu.3.memoryAllocated": 0.0, "system.gpu.0.memoryAllocatedBytes": 4331807266.13, "system.gpu.1.memoryAllocatedBytes": 3145728.0, "system.gpu.2.memoryAllocatedBytes": 3145728.0, "system.gpu.3.memoryAllocatedBytes": 3145728.0, "system.gpu.0.memory": 0.07, "system.gpu.1.memory": 0.0, "system.gpu.2.memory": 0.0, "system.gpu.3.memory": 0.0, "system.gpu.0.gpu": 8.6, "system.gpu.1.gpu": 0.0, "system.gpu.2.gpu": 0.0, "system.gpu.3.gpu": 0.0, "system.gpu.0.temp": 30.2, "system.gpu.1.temp": 28.0, "system.gpu.2.temp": 27.0, "system.gpu.3.temp": 29.0, "system.gpu.0.powerWatts": 76.26, "system.gpu.1.powerWatts": 61.76, "system.gpu.2.powerWatts": 63.01, "system.gpu.3.powerWatts": 62.44, "system.gpu.0.powerPercent": 19.07, "system.gpu.1.powerPercent": 15.44, "system.gpu.2.powerPercent": 15.75, "system.gpu.3.powerPercent": 15.61, "_wandb": true, "_timestamp": 1733140172.955379, "_runtime": 110.381577}']}, 'output.log': {'offset': 38, 'content': ['ERROR 2024-12-02T11:49:35.004754 Traceback (most recent call last):\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt\n', 'ERROR 2024-12-02T11:49:35.004754     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 88, in launch\n', 'ERROR 2024-12-02T11:49:35.004754     return function(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl\n', 'ERROR 2024-12-02T11:49:35.004754     self._run(model, ckpt_path=self.ckpt_path)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run\n', 'ERROR 2024-12-02T11:49:35.004754     results = self._run_stage()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage\n', 'ERROR 2024-12-02T11:49:35.004754     self._run_train()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train\n', 'ERROR 2024-12-02T11:49:35.004754     self.fit_loop.run()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run\n', 'ERROR 2024-12-02T11:49:35.004754     self.advance(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance\n', 'ERROR 2024-12-02T11:49:35.004754     self._outputs = self.epoch_loop.run(self._data_fetcher)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run\n', 'ERROR 2024-12-02T11:49:35.004754     self.advance(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 213, in advance\n', 'ERROR 2024-12-02T11:49:35.004754     batch_output = self.batch_loop.run(kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run\n', 'ERROR 2024-12-02T11:49:35.004754     self.advance(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance\n', 'ERROR 2024-12-02T11:49:35.004754     outputs = self.optimizer_loop.run(optimizers, kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run\n', 'ERROR 2024-12-02T11:49:35.004754     self.advance(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 202, in advance\n', 'ERROR 2024-12-02T11:49:35.004754     result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 241, in _run_optimization\n', 'ERROR 2024-12-02T11:49:35.004754     closure()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 149, in __call__\n', 'ERROR 2024-12-02T11:49:35.004754     self._result = self.closure(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 135, in closure\n', 'ERROR 2024-12-02T11:49:35.004754     step_output = self._step_fn()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 419, in _training_step\n', 'ERROR 2024-12-02T11:49:35.004754     training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1494, in _call_strategy_hook\n', 'ERROR 2024-12-02T11:49:35.004754     output = fn(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py", line 351, in training_step\n', 'ERROR 2024-12-02T11:49:35.004754     return self.model(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     output = self._run_ddp_forward(*inputs, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward\n', 'ERROR 2024-12-02T11:49:35.004754     return module_to_run(*inputs[0], **kwargs[0])\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/overrides/base.py", line 98, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     output = self._forward_module.training_step(*inputs, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/abstract_model.py", line 148, in training_step\n', 'ERROR 2024-12-02T11:49:35.004754     outputs = self(**inputs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/bfn/bfn_regression_model.py", line 41, in forward\n', "ERROR 2024-12-02T11:49:35.004754     logits = self.model(inputs['input_ids']).squeeze(dim=-1)\n", 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/bfn/bfn_model.py", line 105, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     bfn_last_hidden_state = self.bfn(input_ids, return_last_hidden_state=True)[1]\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/bfn/bfn_model.py", line 63, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     outputs = self.net(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/bfn/esm_bfn.py", line 124, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     pred_logits, extra = self.bfn_encoder.forward(t, bfn_pmf, src_lengths, return_last_hidden=True)    # [B, T, V]\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/models/roberta/bfn_roberta.py", line 749, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     x, extra = self.extract_features(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/models/roberta/bfn_roberta.py", line 777, in extract_features\n', 'ERROR 2024-12-02T11:49:35.004754     encoder_out = self.sentence_encoder(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/models/transformer/bfn_transformer_encoder.py", line 228, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     return self.forward_scriptable(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/models/transformer/bfn_transformer_encoder.py", line 333, in forward_scriptable\n', 'ERROR 2024-12-02T11:49:35.004754     lr, attn = layer(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/modules/esm2_transformer_layer.py", line 200, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     x, attn = self.self_attn(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/modules/rotary_multihead_attention.py", line 438, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     attn_weights = attn_weights_float.type_as(attn_weights)\n', 'ERROR 2024-12-02T11:49:35.004754 torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 79.35 GiB total capacity; 72.90 GiB already allocated; 6.19 MiB free; 74.74 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF\n', 'ERROR 2024-12-02T11:49:35.004754 During handling of the above exception, another exception occurred:\n', 'ERROR 2024-12-02T11:49:35.004754 Traceback (most recent call last):\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/training.py", line 93, in <module>\n', 'ERROR 2024-12-02T11:49:35.004754     main()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/training.py", line 88, in main\n', 'ERROR 2024-12-02T11:49:35.004754     run(config)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/training.py", line 30, in run\n', 'ERROR 2024-12-02T11:49:35.004754     trainer.fit(model=model, datamodule=data_module)#, ckpt_path=config.model.save_path)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit\n', 'ERROR 2024-12-02T11:49:35.004754     call._call_and_handle_interrupt(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 59, in _call_and_handle_interrupt\n', 'ERROR 2024-12-02T11:49:35.004754     trainer.strategy.reconciliate_processes(traceback.format_exc())\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py", line 460, in reconciliate_processes\n', 'ERROR 2024-12-02T11:49:35.004754     raise DeadlockDetectedException(f"DeadLock detected from rank: {self.global_rank} \\n {trace}")\n', 'ERROR 2024-12-02T11:49:35.004754 pytorch_lightning.utilities.exceptions.DeadlockDetectedException: DeadLock detected from rank: 0\n', 'ERROR 2024-12-02T11:49:35.004754  Traceback (most recent call last):\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt\n', 'ERROR 2024-12-02T11:49:35.004754     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 88, in launch\n', 'ERROR 2024-12-02T11:49:35.004754     return function(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl\n', 'ERROR 2024-12-02T11:49:35.004754     self._run(model, ckpt_path=self.ckpt_path)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run\n', 'ERROR 2024-12-02T11:49:35.004754     results = self._run_stage()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage\n', 'ERROR 2024-12-02T11:49:35.004754     self._run_train()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train\n', 'ERROR 2024-12-02T11:49:35.004754     self.fit_loop.run()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run\n', 'ERROR 2024-12-02T11:49:35.004754     self.advance(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance\n', 'ERROR 2024-12-02T11:49:35.004754     self._outputs = self.epoch_loop.run(self._data_fetcher)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run\n', 'ERROR 2024-12-02T11:49:35.004754     self.advance(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 213, in advance\n', 'ERROR 2024-12-02T11:49:35.004754     batch_output = self.batch_loop.run(kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run\n', 'ERROR 2024-12-02T11:49:35.004754     self.advance(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance\n', 'ERROR 2024-12-02T11:49:35.004754     outputs = self.optimizer_loop.run(optimizers, kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run\n', 'ERROR 2024-12-02T11:49:35.004754     self.advance(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 202, in advance\n', 'ERROR 2024-12-02T11:49:35.004754     result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 241, in _run_optimization\n', 'ERROR 2024-12-02T11:49:35.004754     closure()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 149, in __call__\n', 'ERROR 2024-12-02T11:49:35.004754     self._result = self.closure(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 135, in closure\n', 'ERROR 2024-12-02T11:49:35.004754     step_output = self._step_fn()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 419, in _training_step\n', 'ERROR 2024-12-02T11:49:35.004754     training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1494, in _call_strategy_hook\n', 'ERROR 2024-12-02T11:49:35.004754     output = fn(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py", line 351, in training_step\n', 'ERROR 2024-12-02T11:49:35.004754     return self.model(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     output = self._run_ddp_forward(*inputs, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward\n', 'ERROR 2024-12-02T11:49:35.004754     return module_to_run(*inputs[0], **kwargs[0])\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/overrides/base.py", line 98, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     output = self._forward_module.training_step(*inputs, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/abstract_model.py", line 148, in training_step\n', 'ERROR 2024-12-02T11:49:35.004754     outputs = self(**inputs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/bfn/bfn_regression_model.py", line 41, in forward\n', "ERROR 2024-12-02T11:49:35.004754     logits = self.model(inputs['input_ids']).squeeze(dim=-1)\n", 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/bfn/bfn_model.py", line 105, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     bfn_last_hidden_state = self.bfn(input_ids, return_last_hidden_state=True)[1]\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/bfn/bfn_model.py", line 63, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     outputs = self.net(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/bfn/esm_bfn.py", line 124, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     pred_logits, extra = self.bfn_encoder.forward(t, bfn_pmf, src_lengths, return_last_hidden=True)    # [B, T, V]\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/models/roberta/bfn_roberta.py", line 749, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     x, extra = self.extract_features(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/models/roberta/bfn_roberta.py", line 777, in extract_features\n', 'ERROR 2024-12-02T11:49:35.004754     encoder_out = self.sentence_encoder(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/models/transformer/bfn_transformer_encoder.py", line 228, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     return self.forward_scriptable(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/models/transformer/bfn_transformer_encoder.py", line 333, in forward_scriptable\n', 'ERROR 2024-12-02T11:49:35.004754     lr, attn = layer(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/modules/esm2_transformer_layer.py", line 200, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     x, attn = self.self_attn(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/modules/rotary_multihead_attention.py", line 438, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     attn_weights = attn_weights_float.type_as(attn_weights)\n', 'ERROR 2024-12-02T11:49:35.004754 torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 79.35 GiB total capacity; 72.90 GiB already allocated; 6.19 MiB free; 74.74 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF\n']}}, 'dropped': 0}}
2024-12-02 11:51:12,636 INFO    wandb-upload_2:1845 [upload_job.py:push():131] Uploaded file ./wandb/run-20241202_114742-wrx7vlmb/files/requirements.txt
2024-12-02 11:51:17,821 INFO    wandb-upload_0:1845 [upload_job.py:push():131] Uploaded file ./wandb/run-20241202_114742-wrx7vlmb/files/conda-environment.yaml
2024-12-02 11:51:39,969 INFO    wandb-upload_1:1845 [upload_job.py:push():131] Uploaded file ./wandb/run-20241202_114742-wrx7vlmb/files/config.yaml
2024-12-02 11:51:40,405 INFO    SenderThread:1845 [file_stream.py:finish():614] file stream finish called
2024-12-02 11:52:01,708 WARNING FileStreamThread:1845 [file_stream.py:request_with_retry():687] requests_with_retry encountered retryable exception: 408 Client Error: Request Timeout for url: https://api.wandb.ai/files/algomole/Thermostability/wrx7vlmb/file_stream. func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x7f709159b160>>, timeout=180.0), args: ('https://api.wandb.ai/files/algomole/Thermostability/wrx7vlmb/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{"_wandb": {"runtime": 44}}']}, 'wandb-events.jsonl': {'offset': 0, 'content': ['{"system.network.sent": 1968795.75, "system.network.recv": 1965425.12, "system.cpu": 1.04, "system.cpu.0.cpu_percent": 14.89, "system.cpu.1.cpu_percent": 1.39, "system.cpu.2.cpu_percent": 2.38, "system.cpu.3.cpu_percent": 1.75, "system.cpu.4.cpu_percent": 2.56, "system.cpu.5.cpu_percent": 7.5, "system.cpu.6.cpu_percent": 2.12, "system.cpu.7.cpu_percent": 1.19, "system.cpu.8.cpu_percent": 1.88, "system.cpu.9.cpu_percent": 1.06, "system.cpu.10.cpu_percent": 2.19, "system.cpu.11.cpu_percent": 1.31, "system.cpu.12.cpu_percent": 1.94, "system.cpu.13.cpu_percent": 1.0, "system.cpu.14.cpu_percent": 4.75, "system.cpu.15.cpu_percent": 2.62, "system.cpu.16.cpu_percent": 2.19, "system.cpu.17.cpu_percent": 1.56, "system.cpu.18.cpu_percent": 5.85, "system.cpu.19.cpu_percent": 1.06, "system.cpu.20.cpu_percent": 34.41, "system.cpu.21.cpu_percent": 1.31, "system.cpu.22.cpu_percent": 8.51, "system.cpu.23.cpu_percent": 1.12, "system.cpu.24.cpu_percent": 27.81, "system.cpu.25.cpu_percent": 1.56, "system.cpu.26.cpu_percent": 2.81, "system.cpu.27.cpu_percent": 1.38, "system.cpu.28.cpu_percent": 3.31, "system.cpu.29.cpu_percent": 2.38, "system.cpu.30.cpu_percent": 4.8, "system.cpu.31.cpu_percent": 1.19, "system.cpu.32.cpu_percent": 10.11, "system.cpu.33.cpu_percent": 1.38, "system.cpu.34.cpu_percent": 4.05, "system.cpu.35.cpu_percent": 1.06, "system.cpu.36.cpu_percent": 12.14, "system.cpu.37.cpu_percent": 1.19, "system.cpu.38.cpu_percent": 4.65, "system.cpu.39.cpu_percent": 1.12, "system.cpu.40.cpu_percent": 2.88, "system.cpu.41.cpu_percent": 1.06, "system.cpu.42.cpu_percent": 21.11, "system.cpu.43.cpu_percent": 1.06, "system.cpu.44.cpu_percent": 23.07, "system.cpu.45.cpu_percent": 1.69, "system.cpu.46.cpu_percent": 7.38, "system.cpu.47.cpu_percent": 45.81, "system.cpu.48.cpu_percent": 12.49, "system.cpu.49.cpu_percent": 0.94, "system.cpu.50.cpu_percent": 16.24, "system.cpu.51.cpu_percent": 1.06, "system.cpu.52.cpu_percent": 1.5, "system.cpu.53.cpu_percent": 51.2, "system.cpu.54.cpu_percent": 1.94, "system.cpu.55.cpu_percent": 25.67, "system.cpu.56.cpu_percent": 12.59, "system.cpu.57.cpu_percent": 1.31, "system.cpu.58.cpu_percent": 27.06, "system.cpu.59.cpu_percent": 25.94, "system.cpu.60.cpu_percent": 2.44, "system.cpu.61.cpu_percent": 1.31, "system.cpu.62.cpu_percent": 5.45, "system.cpu.63.cpu_percent": 2.06, "system.cpu.64.cpu_percent": 2.38, "system.cpu.65.cpu_percent": 1.62, "system.cpu.66.cpu_percent": 2.88, "system.cpu.67.cpu_percent": 1.31, "system.cpu.68.cpu_percent": 44.03, "system.cpu.69.cpu_percent": 1.25, "system.cpu.70.cpu_percent": 12.3, "system.cpu.71.cpu_percent": 1.38, "system.cpu.72.cpu_percent": 2.19, "system.cpu.73.cpu_percent": 6.59, "system.cpu.74.cpu_percent": 6.79, "system.cpu.75.cpu_percent": 1.5, "system.cpu.76.cpu_percent": 43.95, "system.cpu.77.cpu_percent": 1.44, "system.cpu.78.cpu_percent": 11.24, "system.cpu.79.cpu_percent": 3.06, "system.cpu.80.cpu_percent": 2.38, "system.cpu.81.cpu_percent": 1.5, "system.cpu.82.cpu_percent": 7.55, "system.cpu.83.cpu_percent": 1.19, "system.cpu.84.cpu_percent": 16.52, "system.cpu.85.cpu_percent": 1.25, "system.cpu.86.cpu_percent": 2.19, "system.cpu.87.cpu_percent": 1.81, "system.cpu.88.cpu_percent": 3.12, "system.cpu.89.cpu_percent": 1.31, "system.cpu.90.cpu_percent": 3.0, "system.cpu.91.cpu_percent": 2.12, "system.cpu.92.cpu_percent": 16.23, "system.cpu.93.cpu_percent": 1.19, "system.cpu.94.cpu_percent": 26.04, "system.cpu.95.cpu_percent": 1.44, "system.cpu.96.cpu_percent": 17.49, "system.cpu.97.cpu_percent": 1.38, "system.cpu.98.cpu_percent": 2.31, "system.cpu.99.cpu_percent": 3.0, "system.cpu.100.cpu_percent": 9.64, "system.cpu.101.cpu_percent": 1.75, "system.cpu.102.cpu_percent": 2.0, "system.cpu.103.cpu_percent": 1.56, "system.cpu.104.cpu_percent": 2.06, "system.cpu.105.cpu_percent": 1.94, "system.cpu.106.cpu_percent": 1.69, "system.cpu.107.cpu_percent": 40.56, "system.cpu.108.cpu_percent": 15.8, "system.cpu.109.cpu_percent": 1.38, "system.cpu.110.cpu_percent": 11.55, "system.cpu.111.cpu_percent": 5.26, "system.proc.cpu.threads": 21, "system.disk.\\\\.usagePercent": 18.5, "system.disk.\\\\.usageGB": 618.77, "system.disk.in": 0.97, "system.disk.out": 7.71, "system.proc.memory.availableMB": 912332.14, "system.memory": 4.21, "system.proc.memory.rssMB": 10199.95, "system.proc.memory.percent": 1.07, "system.gpu.0.memoryAllocated": 5.08, "system.gpu.1.memoryAllocated": 0.0, "system.gpu.2.memoryAllocated": 0.0, "system.gpu.3.memoryAllocated": 0.0, "system.gpu.0.memoryAllocatedBytes": 4331807266.13, "system.gpu.1.memoryAllocatedBytes": 3145728.0, "system.gpu.2.memoryAllocatedBytes": 3145728.0, "system.gpu.3.memoryAllocatedBytes": 3145728.0, "system.gpu.0.memory": 0.07, "system.gpu.1.memory": 0.0, "system.gpu.2.memory": 0.0, "system.gpu.3.memory": 0.0, "system.gpu.0.gpu": 8.6, "system.gpu.1.gpu": 0.0, "system.gpu.2.gpu": 0.0, "system.gpu.3.gpu": 0.0, "system.gpu.0.temp": 30.2, "system.gpu.1.temp": 28.0, "system.gpu.2.temp": 27.0, "system.gpu.3.temp": 29.0, "system.gpu.0.powerWatts": 76.26, "system.gpu.1.powerWatts": 61.76, "system.gpu.2.powerWatts": 63.01, "system.gpu.3.powerWatts": 62.44, "system.gpu.0.powerPercent": 19.07, "system.gpu.1.powerPercent": 15.44, "system.gpu.2.powerPercent": 15.75, "system.gpu.3.powerPercent": 15.61, "_wandb": true, "_timestamp": 1733140172.955379, "_runtime": 110.381577}']}, 'output.log': {'offset': 38, 'content': ['ERROR 2024-12-02T11:49:35.004754 Traceback (most recent call last):\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt\n', 'ERROR 2024-12-02T11:49:35.004754     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 88, in launch\n', 'ERROR 2024-12-02T11:49:35.004754     return function(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl\n', 'ERROR 2024-12-02T11:49:35.004754     self._run(model, ckpt_path=self.ckpt_path)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run\n', 'ERROR 2024-12-02T11:49:35.004754     results = self._run_stage()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage\n', 'ERROR 2024-12-02T11:49:35.004754     self._run_train()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train\n', 'ERROR 2024-12-02T11:49:35.004754     self.fit_loop.run()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run\n', 'ERROR 2024-12-02T11:49:35.004754     self.advance(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance\n', 'ERROR 2024-12-02T11:49:35.004754     self._outputs = self.epoch_loop.run(self._data_fetcher)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run\n', 'ERROR 2024-12-02T11:49:35.004754     self.advance(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 213, in advance\n', 'ERROR 2024-12-02T11:49:35.004754     batch_output = self.batch_loop.run(kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run\n', 'ERROR 2024-12-02T11:49:35.004754     self.advance(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance\n', 'ERROR 2024-12-02T11:49:35.004754     outputs = self.optimizer_loop.run(optimizers, kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run\n', 'ERROR 2024-12-02T11:49:35.004754     self.advance(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 202, in advance\n', 'ERROR 2024-12-02T11:49:35.004754     result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 241, in _run_optimization\n', 'ERROR 2024-12-02T11:49:35.004754     closure()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 149, in __call__\n', 'ERROR 2024-12-02T11:49:35.004754     self._result = self.closure(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 135, in closure\n', 'ERROR 2024-12-02T11:49:35.004754     step_output = self._step_fn()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 419, in _training_step\n', 'ERROR 2024-12-02T11:49:35.004754     training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1494, in _call_strategy_hook\n', 'ERROR 2024-12-02T11:49:35.004754     output = fn(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py", line 351, in training_step\n', 'ERROR 2024-12-02T11:49:35.004754     return self.model(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     output = self._run_ddp_forward(*inputs, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward\n', 'ERROR 2024-12-02T11:49:35.004754     return module_to_run(*inputs[0], **kwargs[0])\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/overrides/base.py", line 98, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     output = self._forward_module.training_step(*inputs, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/abstract_model.py", line 148, in training_step\n', 'ERROR 2024-12-02T11:49:35.004754     outputs = self(**inputs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/bfn/bfn_regression_model.py", line 41, in forward\n', "ERROR 2024-12-02T11:49:35.004754     logits = self.model(inputs['input_ids']).squeeze(dim=-1)\n", 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/bfn/bfn_model.py", line 105, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     bfn_last_hidden_state = self.bfn(input_ids, return_last_hidden_state=True)[1]\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/bfn/bfn_model.py", line 63, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     outputs = self.net(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/bfn/esm_bfn.py", line 124, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     pred_logits, extra = self.bfn_encoder.forward(t, bfn_pmf, src_lengths, return_last_hidden=True)    # [B, T, V]\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/models/roberta/bfn_roberta.py", line 749, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     x, extra = self.extract_features(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/models/roberta/bfn_roberta.py", line 777, in extract_features\n', 'ERROR 2024-12-02T11:49:35.004754     encoder_out = self.sentence_encoder(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/models/transformer/bfn_transformer_encoder.py", line 228, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     return self.forward_scriptable(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/models/transformer/bfn_transformer_encoder.py", line 333, in forward_scriptable\n', 'ERROR 2024-12-02T11:49:35.004754     lr, attn = layer(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/modules/esm2_transformer_layer.py", line 200, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     x, attn = self.self_attn(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/modules/rotary_multihead_attention.py", line 438, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     attn_weights = attn_weights_float.type_as(attn_weights)\n', 'ERROR 2024-12-02T11:49:35.004754 torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 79.35 GiB total capacity; 72.90 GiB already allocated; 6.19 MiB free; 74.74 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF\n', 'ERROR 2024-12-02T11:49:35.004754 During handling of the above exception, another exception occurred:\n', 'ERROR 2024-12-02T11:49:35.004754 Traceback (most recent call last):\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/training.py", line 93, in <module>\n', 'ERROR 2024-12-02T11:49:35.004754     main()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/training.py", line 88, in main\n', 'ERROR 2024-12-02T11:49:35.004754     run(config)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/training.py", line 30, in run\n', 'ERROR 2024-12-02T11:49:35.004754     trainer.fit(model=model, datamodule=data_module)#, ckpt_path=config.model.save_path)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit\n', 'ERROR 2024-12-02T11:49:35.004754     call._call_and_handle_interrupt(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 59, in _call_and_handle_interrupt\n', 'ERROR 2024-12-02T11:49:35.004754     trainer.strategy.reconciliate_processes(traceback.format_exc())\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py", line 460, in reconciliate_processes\n', 'ERROR 2024-12-02T11:49:35.004754     raise DeadlockDetectedException(f"DeadLock detected from rank: {self.global_rank} \\n {trace}")\n', 'ERROR 2024-12-02T11:49:35.004754 pytorch_lightning.utilities.exceptions.DeadlockDetectedException: DeadLock detected from rank: 0\n', 'ERROR 2024-12-02T11:49:35.004754  Traceback (most recent call last):\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt\n', 'ERROR 2024-12-02T11:49:35.004754     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 88, in launch\n', 'ERROR 2024-12-02T11:49:35.004754     return function(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl\n', 'ERROR 2024-12-02T11:49:35.004754     self._run(model, ckpt_path=self.ckpt_path)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run\n', 'ERROR 2024-12-02T11:49:35.004754     results = self._run_stage()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage\n', 'ERROR 2024-12-02T11:49:35.004754     self._run_train()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train\n', 'ERROR 2024-12-02T11:49:35.004754     self.fit_loop.run()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run\n', 'ERROR 2024-12-02T11:49:35.004754     self.advance(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance\n', 'ERROR 2024-12-02T11:49:35.004754     self._outputs = self.epoch_loop.run(self._data_fetcher)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run\n', 'ERROR 2024-12-02T11:49:35.004754     self.advance(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 213, in advance\n', 'ERROR 2024-12-02T11:49:35.004754     batch_output = self.batch_loop.run(kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run\n', 'ERROR 2024-12-02T11:49:35.004754     self.advance(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance\n', 'ERROR 2024-12-02T11:49:35.004754     outputs = self.optimizer_loop.run(optimizers, kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run\n', 'ERROR 2024-12-02T11:49:35.004754     self.advance(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 202, in advance\n', 'ERROR 2024-12-02T11:49:35.004754     result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 241, in _run_optimization\n', 'ERROR 2024-12-02T11:49:35.004754     closure()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 149, in __call__\n', 'ERROR 2024-12-02T11:49:35.004754     self._result = self.closure(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 135, in closure\n', 'ERROR 2024-12-02T11:49:35.004754     step_output = self._step_fn()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 419, in _training_step\n', 'ERROR 2024-12-02T11:49:35.004754     training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1494, in _call_strategy_hook\n', 'ERROR 2024-12-02T11:49:35.004754     output = fn(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py", line 351, in training_step\n', 'ERROR 2024-12-02T11:49:35.004754     return self.model(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     output = self._run_ddp_forward(*inputs, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward\n', 'ERROR 2024-12-02T11:49:35.004754     return module_to_run(*inputs[0], **kwargs[0])\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/overrides/base.py", line 98, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     output = self._forward_module.training_step(*inputs, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/abstract_model.py", line 148, in training_step\n', 'ERROR 2024-12-02T11:49:35.004754     outputs = self(**inputs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/bfn/bfn_regression_model.py", line 41, in forward\n', "ERROR 2024-12-02T11:49:35.004754     logits = self.model(inputs['input_ids']).squeeze(dim=-1)\n", 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/bfn/bfn_model.py", line 105, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     bfn_last_hidden_state = self.bfn(input_ids, return_last_hidden_state=True)[1]\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/bfn/bfn_model.py", line 63, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     outputs = self.net(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/bfn/esm_bfn.py", line 124, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     pred_logits, extra = self.bfn_encoder.forward(t, bfn_pmf, src_lengths, return_last_hidden=True)    # [B, T, V]\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/models/roberta/bfn_roberta.py", line 749, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     x, extra = self.extract_features(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/models/roberta/bfn_roberta.py", line 777, in extract_features\n', 'ERROR 2024-12-02T11:49:35.004754     encoder_out = self.sentence_encoder(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/models/transformer/bfn_transformer_encoder.py", line 228, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     return self.forward_scriptable(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/models/transformer/bfn_transformer_encoder.py", line 333, in forward_scriptable\n', 'ERROR 2024-12-02T11:49:35.004754     lr, attn = layer(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/modules/esm2_transformer_layer.py", line 200, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     x, attn = self.self_attn(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/modules/rotary_multihead_attention.py", line 438, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     attn_weights = attn_weights_float.type_as(attn_weights)\n', 'ERROR 2024-12-02T11:49:35.004754 torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 79.35 GiB total capacity; 72.90 GiB already allocated; 6.19 MiB free; 74.74 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF\n']}}, 'dropped': 0}}
2024-12-02 11:54:16,279 WARNING FileStreamThread:1845 [file_stream.py:request_with_retry():687] requests_with_retry encountered retryable exception: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /files/algomole/Thermostability/wrx7vlmb/file_stream (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f70913c3640>: Failed to establish a new connection: [Errno 110] Connection timed out')). func: functools.partial(<bound method Session.post of <requests.sessions.Session object at 0x7f709159b160>>, timeout=180.0), args: ('https://api.wandb.ai/files/algomole/Thermostability/wrx7vlmb/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{"_wandb": {"runtime": 44}}']}, 'wandb-events.jsonl': {'offset': 0, 'content': ['{"system.network.sent": 1968795.75, "system.network.recv": 1965425.12, "system.cpu": 1.04, "system.cpu.0.cpu_percent": 14.89, "system.cpu.1.cpu_percent": 1.39, "system.cpu.2.cpu_percent": 2.38, "system.cpu.3.cpu_percent": 1.75, "system.cpu.4.cpu_percent": 2.56, "system.cpu.5.cpu_percent": 7.5, "system.cpu.6.cpu_percent": 2.12, "system.cpu.7.cpu_percent": 1.19, "system.cpu.8.cpu_percent": 1.88, "system.cpu.9.cpu_percent": 1.06, "system.cpu.10.cpu_percent": 2.19, "system.cpu.11.cpu_percent": 1.31, "system.cpu.12.cpu_percent": 1.94, "system.cpu.13.cpu_percent": 1.0, "system.cpu.14.cpu_percent": 4.75, "system.cpu.15.cpu_percent": 2.62, "system.cpu.16.cpu_percent": 2.19, "system.cpu.17.cpu_percent": 1.56, "system.cpu.18.cpu_percent": 5.85, "system.cpu.19.cpu_percent": 1.06, "system.cpu.20.cpu_percent": 34.41, "system.cpu.21.cpu_percent": 1.31, "system.cpu.22.cpu_percent": 8.51, "system.cpu.23.cpu_percent": 1.12, "system.cpu.24.cpu_percent": 27.81, "system.cpu.25.cpu_percent": 1.56, "system.cpu.26.cpu_percent": 2.81, "system.cpu.27.cpu_percent": 1.38, "system.cpu.28.cpu_percent": 3.31, "system.cpu.29.cpu_percent": 2.38, "system.cpu.30.cpu_percent": 4.8, "system.cpu.31.cpu_percent": 1.19, "system.cpu.32.cpu_percent": 10.11, "system.cpu.33.cpu_percent": 1.38, "system.cpu.34.cpu_percent": 4.05, "system.cpu.35.cpu_percent": 1.06, "system.cpu.36.cpu_percent": 12.14, "system.cpu.37.cpu_percent": 1.19, "system.cpu.38.cpu_percent": 4.65, "system.cpu.39.cpu_percent": 1.12, "system.cpu.40.cpu_percent": 2.88, "system.cpu.41.cpu_percent": 1.06, "system.cpu.42.cpu_percent": 21.11, "system.cpu.43.cpu_percent": 1.06, "system.cpu.44.cpu_percent": 23.07, "system.cpu.45.cpu_percent": 1.69, "system.cpu.46.cpu_percent": 7.38, "system.cpu.47.cpu_percent": 45.81, "system.cpu.48.cpu_percent": 12.49, "system.cpu.49.cpu_percent": 0.94, "system.cpu.50.cpu_percent": 16.24, "system.cpu.51.cpu_percent": 1.06, "system.cpu.52.cpu_percent": 1.5, "system.cpu.53.cpu_percent": 51.2, "system.cpu.54.cpu_percent": 1.94, "system.cpu.55.cpu_percent": 25.67, "system.cpu.56.cpu_percent": 12.59, "system.cpu.57.cpu_percent": 1.31, "system.cpu.58.cpu_percent": 27.06, "system.cpu.59.cpu_percent": 25.94, "system.cpu.60.cpu_percent": 2.44, "system.cpu.61.cpu_percent": 1.31, "system.cpu.62.cpu_percent": 5.45, "system.cpu.63.cpu_percent": 2.06, "system.cpu.64.cpu_percent": 2.38, "system.cpu.65.cpu_percent": 1.62, "system.cpu.66.cpu_percent": 2.88, "system.cpu.67.cpu_percent": 1.31, "system.cpu.68.cpu_percent": 44.03, "system.cpu.69.cpu_percent": 1.25, "system.cpu.70.cpu_percent": 12.3, "system.cpu.71.cpu_percent": 1.38, "system.cpu.72.cpu_percent": 2.19, "system.cpu.73.cpu_percent": 6.59, "system.cpu.74.cpu_percent": 6.79, "system.cpu.75.cpu_percent": 1.5, "system.cpu.76.cpu_percent": 43.95, "system.cpu.77.cpu_percent": 1.44, "system.cpu.78.cpu_percent": 11.24, "system.cpu.79.cpu_percent": 3.06, "system.cpu.80.cpu_percent": 2.38, "system.cpu.81.cpu_percent": 1.5, "system.cpu.82.cpu_percent": 7.55, "system.cpu.83.cpu_percent": 1.19, "system.cpu.84.cpu_percent": 16.52, "system.cpu.85.cpu_percent": 1.25, "system.cpu.86.cpu_percent": 2.19, "system.cpu.87.cpu_percent": 1.81, "system.cpu.88.cpu_percent": 3.12, "system.cpu.89.cpu_percent": 1.31, "system.cpu.90.cpu_percent": 3.0, "system.cpu.91.cpu_percent": 2.12, "system.cpu.92.cpu_percent": 16.23, "system.cpu.93.cpu_percent": 1.19, "system.cpu.94.cpu_percent": 26.04, "system.cpu.95.cpu_percent": 1.44, "system.cpu.96.cpu_percent": 17.49, "system.cpu.97.cpu_percent": 1.38, "system.cpu.98.cpu_percent": 2.31, "system.cpu.99.cpu_percent": 3.0, "system.cpu.100.cpu_percent": 9.64, "system.cpu.101.cpu_percent": 1.75, "system.cpu.102.cpu_percent": 2.0, "system.cpu.103.cpu_percent": 1.56, "system.cpu.104.cpu_percent": 2.06, "system.cpu.105.cpu_percent": 1.94, "system.cpu.106.cpu_percent": 1.69, "system.cpu.107.cpu_percent": 40.56, "system.cpu.108.cpu_percent": 15.8, "system.cpu.109.cpu_percent": 1.38, "system.cpu.110.cpu_percent": 11.55, "system.cpu.111.cpu_percent": 5.26, "system.proc.cpu.threads": 21, "system.disk.\\\\.usagePercent": 18.5, "system.disk.\\\\.usageGB": 618.77, "system.disk.in": 0.97, "system.disk.out": 7.71, "system.proc.memory.availableMB": 912332.14, "system.memory": 4.21, "system.proc.memory.rssMB": 10199.95, "system.proc.memory.percent": 1.07, "system.gpu.0.memoryAllocated": 5.08, "system.gpu.1.memoryAllocated": 0.0, "system.gpu.2.memoryAllocated": 0.0, "system.gpu.3.memoryAllocated": 0.0, "system.gpu.0.memoryAllocatedBytes": 4331807266.13, "system.gpu.1.memoryAllocatedBytes": 3145728.0, "system.gpu.2.memoryAllocatedBytes": 3145728.0, "system.gpu.3.memoryAllocatedBytes": 3145728.0, "system.gpu.0.memory": 0.07, "system.gpu.1.memory": 0.0, "system.gpu.2.memory": 0.0, "system.gpu.3.memory": 0.0, "system.gpu.0.gpu": 8.6, "system.gpu.1.gpu": 0.0, "system.gpu.2.gpu": 0.0, "system.gpu.3.gpu": 0.0, "system.gpu.0.temp": 30.2, "system.gpu.1.temp": 28.0, "system.gpu.2.temp": 27.0, "system.gpu.3.temp": 29.0, "system.gpu.0.powerWatts": 76.26, "system.gpu.1.powerWatts": 61.76, "system.gpu.2.powerWatts": 63.01, "system.gpu.3.powerWatts": 62.44, "system.gpu.0.powerPercent": 19.07, "system.gpu.1.powerPercent": 15.44, "system.gpu.2.powerPercent": 15.75, "system.gpu.3.powerPercent": 15.61, "_wandb": true, "_timestamp": 1733140172.955379, "_runtime": 110.381577}']}, 'output.log': {'offset': 38, 'content': ['ERROR 2024-12-02T11:49:35.004754 Traceback (most recent call last):\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt\n', 'ERROR 2024-12-02T11:49:35.004754     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 88, in launch\n', 'ERROR 2024-12-02T11:49:35.004754     return function(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl\n', 'ERROR 2024-12-02T11:49:35.004754     self._run(model, ckpt_path=self.ckpt_path)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run\n', 'ERROR 2024-12-02T11:49:35.004754     results = self._run_stage()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage\n', 'ERROR 2024-12-02T11:49:35.004754     self._run_train()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train\n', 'ERROR 2024-12-02T11:49:35.004754     self.fit_loop.run()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run\n', 'ERROR 2024-12-02T11:49:35.004754     self.advance(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance\n', 'ERROR 2024-12-02T11:49:35.004754     self._outputs = self.epoch_loop.run(self._data_fetcher)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run\n', 'ERROR 2024-12-02T11:49:35.004754     self.advance(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 213, in advance\n', 'ERROR 2024-12-02T11:49:35.004754     batch_output = self.batch_loop.run(kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run\n', 'ERROR 2024-12-02T11:49:35.004754     self.advance(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance\n', 'ERROR 2024-12-02T11:49:35.004754     outputs = self.optimizer_loop.run(optimizers, kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run\n', 'ERROR 2024-12-02T11:49:35.004754     self.advance(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 202, in advance\n', 'ERROR 2024-12-02T11:49:35.004754     result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 241, in _run_optimization\n', 'ERROR 2024-12-02T11:49:35.004754     closure()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 149, in __call__\n', 'ERROR 2024-12-02T11:49:35.004754     self._result = self.closure(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 135, in closure\n', 'ERROR 2024-12-02T11:49:35.004754     step_output = self._step_fn()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 419, in _training_step\n', 'ERROR 2024-12-02T11:49:35.004754     training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1494, in _call_strategy_hook\n', 'ERROR 2024-12-02T11:49:35.004754     output = fn(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py", line 351, in training_step\n', 'ERROR 2024-12-02T11:49:35.004754     return self.model(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     output = self._run_ddp_forward(*inputs, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward\n', 'ERROR 2024-12-02T11:49:35.004754     return module_to_run(*inputs[0], **kwargs[0])\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/overrides/base.py", line 98, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     output = self._forward_module.training_step(*inputs, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/abstract_model.py", line 148, in training_step\n', 'ERROR 2024-12-02T11:49:35.004754     outputs = self(**inputs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/bfn/bfn_regression_model.py", line 41, in forward\n', "ERROR 2024-12-02T11:49:35.004754     logits = self.model(inputs['input_ids']).squeeze(dim=-1)\n", 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/bfn/bfn_model.py", line 105, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     bfn_last_hidden_state = self.bfn(input_ids, return_last_hidden_state=True)[1]\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/bfn/bfn_model.py", line 63, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     outputs = self.net(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/bfn/esm_bfn.py", line 124, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     pred_logits, extra = self.bfn_encoder.forward(t, bfn_pmf, src_lengths, return_last_hidden=True)    # [B, T, V]\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/models/roberta/bfn_roberta.py", line 749, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     x, extra = self.extract_features(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/models/roberta/bfn_roberta.py", line 777, in extract_features\n', 'ERROR 2024-12-02T11:49:35.004754     encoder_out = self.sentence_encoder(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/models/transformer/bfn_transformer_encoder.py", line 228, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     return self.forward_scriptable(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/models/transformer/bfn_transformer_encoder.py", line 333, in forward_scriptable\n', 'ERROR 2024-12-02T11:49:35.004754     lr, attn = layer(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/modules/esm2_transformer_layer.py", line 200, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     x, attn = self.self_attn(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/modules/rotary_multihead_attention.py", line 438, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     attn_weights = attn_weights_float.type_as(attn_weights)\n', 'ERROR 2024-12-02T11:49:35.004754 torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 79.35 GiB total capacity; 72.90 GiB already allocated; 6.19 MiB free; 74.74 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF\n', 'ERROR 2024-12-02T11:49:35.004754 During handling of the above exception, another exception occurred:\n', 'ERROR 2024-12-02T11:49:35.004754 Traceback (most recent call last):\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/training.py", line 93, in <module>\n', 'ERROR 2024-12-02T11:49:35.004754     main()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/training.py", line 88, in main\n', 'ERROR 2024-12-02T11:49:35.004754     run(config)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/training.py", line 30, in run\n', 'ERROR 2024-12-02T11:49:35.004754     trainer.fit(model=model, datamodule=data_module)#, ckpt_path=config.model.save_path)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit\n', 'ERROR 2024-12-02T11:49:35.004754     call._call_and_handle_interrupt(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 59, in _call_and_handle_interrupt\n', 'ERROR 2024-12-02T11:49:35.004754     trainer.strategy.reconciliate_processes(traceback.format_exc())\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py", line 460, in reconciliate_processes\n', 'ERROR 2024-12-02T11:49:35.004754     raise DeadlockDetectedException(f"DeadLock detected from rank: {self.global_rank} \\n {trace}")\n', 'ERROR 2024-12-02T11:49:35.004754 pytorch_lightning.utilities.exceptions.DeadlockDetectedException: DeadLock detected from rank: 0\n', 'ERROR 2024-12-02T11:49:35.004754  Traceback (most recent call last):\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt\n', 'ERROR 2024-12-02T11:49:35.004754     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 88, in launch\n', 'ERROR 2024-12-02T11:49:35.004754     return function(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl\n', 'ERROR 2024-12-02T11:49:35.004754     self._run(model, ckpt_path=self.ckpt_path)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run\n', 'ERROR 2024-12-02T11:49:35.004754     results = self._run_stage()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage\n', 'ERROR 2024-12-02T11:49:35.004754     self._run_train()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train\n', 'ERROR 2024-12-02T11:49:35.004754     self.fit_loop.run()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run\n', 'ERROR 2024-12-02T11:49:35.004754     self.advance(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance\n', 'ERROR 2024-12-02T11:49:35.004754     self._outputs = self.epoch_loop.run(self._data_fetcher)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run\n', 'ERROR 2024-12-02T11:49:35.004754     self.advance(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 213, in advance\n', 'ERROR 2024-12-02T11:49:35.004754     batch_output = self.batch_loop.run(kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run\n', 'ERROR 2024-12-02T11:49:35.004754     self.advance(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance\n', 'ERROR 2024-12-02T11:49:35.004754     outputs = self.optimizer_loop.run(optimizers, kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run\n', 'ERROR 2024-12-02T11:49:35.004754     self.advance(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 202, in advance\n', 'ERROR 2024-12-02T11:49:35.004754     result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 241, in _run_optimization\n', 'ERROR 2024-12-02T11:49:35.004754     closure()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 149, in __call__\n', 'ERROR 2024-12-02T11:49:35.004754     self._result = self.closure(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 135, in closure\n', 'ERROR 2024-12-02T11:49:35.004754     step_output = self._step_fn()\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 419, in _training_step\n', 'ERROR 2024-12-02T11:49:35.004754     training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1494, in _call_strategy_hook\n', 'ERROR 2024-12-02T11:49:35.004754     output = fn(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp.py", line 351, in training_step\n', 'ERROR 2024-12-02T11:49:35.004754     return self.model(*args, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     output = self._run_ddp_forward(*inputs, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward\n', 'ERROR 2024-12-02T11:49:35.004754     return module_to_run(*inputs[0], **kwargs[0])\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/pytorch_lightning/overrides/base.py", line 98, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     output = self._forward_module.training_step(*inputs, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/abstract_model.py", line 148, in training_step\n', 'ERROR 2024-12-02T11:49:35.004754     outputs = self(**inputs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/bfn/bfn_regression_model.py", line 41, in forward\n', "ERROR 2024-12-02T11:49:35.004754     logits = self.model(inputs['input_ids']).squeeze(dim=-1)\n", 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/bfn/bfn_model.py", line 105, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     bfn_last_hidden_state = self.bfn(input_ids, return_last_hidden_state=True)[1]\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/bfn/bfn_model.py", line 63, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     outputs = self.net(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/represent_learning/model/bfn/esm_bfn.py", line 124, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     pred_logits, extra = self.bfn_encoder.forward(t, bfn_pmf, src_lengths, return_last_hidden=True)    # [B, T, V]\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/models/roberta/bfn_roberta.py", line 749, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     x, extra = self.extract_features(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/models/roberta/bfn_roberta.py", line 777, in extract_features\n', 'ERROR 2024-12-02T11:49:35.004754     encoder_out = self.sentence_encoder(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/models/transformer/bfn_transformer_encoder.py", line 228, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     return self.forward_scriptable(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/models/transformer/bfn_transformer_encoder.py", line 333, in forward_scriptable\n', 'ERROR 2024-12-02T11:49:35.004754     lr, attn = layer(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/modules/esm2_transformer_layer.py", line 200, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     x, attn = self.self_attn(\n', 'ERROR 2024-12-02T11:49:35.004754   File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl\n', 'ERROR 2024-12-02T11:49:35.004754     return forward_call(*input, **kwargs)\n', 'ERROR 2024-12-02T11:49:35.004754   File "/AIRvePFS/ai4science/users/yupei/ProfileBFN-pro/fairseq/modules/rotary_multihead_attention.py", line 438, in forward\n', 'ERROR 2024-12-02T11:49:35.004754     attn_weights = attn_weights_float.type_as(attn_weights)\n', 'ERROR 2024-12-02T11:49:35.004754 torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 79.35 GiB total capacity; 72.90 GiB already allocated; 6.19 MiB free; 74.74 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF\n']}}, 'dropped': 0}}
2024-12-02 11:54:52,774 INFO    SenderThread:1845 [file_stream.py:finish():618] file stream finish is done
